import { test, expect } from '@playwright/test';
import { PublishCarPage } from '../pages/cars/PublishCarPage';
import path from 'path';

test.describe('Owner Car Publication Flow', () => {
  // Use the owner auth state generated by global-setup
  test.use({ storageState: 'tests/.auth/owner.json' });

  test('should publish a new car successfully', async ({ page }) => {
    const publishPage = new PublishCarPage(page);

    // 1. Navigate directly to publish page (State Hydration)
    await publishPage.goto();

    // Handle potential auth failure (fallback)
    if (page.url().includes('/auth/login')) {
      console.log('⚠️ Auth state invalid/expired, performing manual login fallback...');
      const emailInput = page.getByPlaceholder(/email|correo/i).first();
      const passwordInput = page.getByPlaceholder(/contraseña|password/i).first();
      
      // Try the credentials from global-setup first, then the alternative
      await emailInput.fill('owner.dashboard@example.com'); 
      await passwordInput.fill('TestOwnerDashboard123!');
      
      await page.getByRole('button', { name: /entrar|iniciar|login/i }).click();
      
      // Wait for redirect back to publish or dashboard then navigate
      await page.waitForURL(/(cars|dashboard)/);
      await publishPage.goto();
    }

    // 2. Fill Vehicle Data
    console.log('🚗 Filling vehicle data...');
    // Note: Using known values that likely exist in the FIPE mock/API
    await publishPage.selectBrand('Toyota'); 
    await publishPage.selectModel('Corolla');
    await publishPage.fillYear(2022);
    
    await publishPage.fillVehicleDetails({
      mileage: 25000,
      color: 'Gris Plata',
      transmission: 'Automática',
      fuel: 'nafta'
    });

    // 3. Configure Pricing
    console.log('💰 Configuring pricing...');
    await publishPage.configurePricing(18000); // $18,000 ARS per day

    // 4. Fill Location
    console.log('📍 Setting location...');
    await publishPage.fillLocation({
      street: 'Av. Libertador',
      number: '4500',
      city: 'Buenos Aires',
      state: 'CABA',
      country: 'Argentina' // Optional if select has default
    });

    // 5. Upload Photos
    console.log('📸 Uploading photos...');
    const imagesDir = path.join(__dirname, '../fixtures/images');
    const photoPaths = [
      path.join(imagesDir, 'porsche-front.jpg'),
      path.join(imagesDir, 'porsche-side.jpg'),
      path.join(imagesDir, 'porsche-interior.jpg')
    ];
    await publishPage.uploadPhotos(photoPaths);

    // 6. Submit
    console.log('🚀 Submitting publication...');
    await publishPage.submit();

    // 7. Verify Success
    console.log('✅ Verifying redirection and creation...');
    await publishPage.assertRedirectedToMyCars();
    
    // Verify the new car appears in the list (might need reload or wait)
    await expect(page.getByText('Toyota Corolla').first()).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('2022')).toBeVisible(); // Year check
  });
});
