#!/usr/bin/env node

/**
 * Generates public/env.js with runtime environment variables
 * This allows Angular to read config in the browser via window.__env
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env files
require('dotenv').config({ path: path.join(__dirname, '../.env.development.local') });
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const envVars = {
  NG_APP_SUPABASE_URL: process.env.NG_APP_SUPABASE_URL || '',
  NG_APP_SUPABASE_ANON_KEY: process.env.NG_APP_SUPABASE_ANON_KEY || '',
  NG_APP_DEFAULT_CURRENCY: process.env.NG_APP_DEFAULT_CURRENCY || 'ARS',
  NG_APP_PAYMENTS_WEBHOOK_URL: process.env.NG_APP_PAYMENTS_WEBHOOK_URL || '',
  NG_APP_MAPBOX_ACCESS_TOKEN: process.env.NG_APP_MAPBOX_ACCESS_TOKEN || '',
  NG_APP_CAR_LOCATIONS_EDGE_FUNCTION: process.env.NG_APP_CAR_LOCATIONS_EDGE_FUNCTION || '',
  NG_APP_MERCADOPAGO_PUBLIC_KEY:
    process.env.NG_APP_MERCADOPAGO_PUBLIC_KEY ||
    process.env.MERCADOPAGO_PUBLIC_KEY ||
    '',
  NG_APP_CLOUDFLARE_WORKER_URL: process.env.NG_APP_CLOUDFLARE_WORKER_URL || 'https://autorent-ai-car-generator.marques-eduardo95466020.workers.dev'
};

const envJsContent = `// Auto-generated environment configuration
// This file is generated by scripts/generate-env.js during build
// DO NOT EDIT MANUALLY
window.__env = ${JSON.stringify(envVars, null, 2)};
`;

const outputPath = path.join(__dirname, '../public/env.js');
fs.writeFileSync(outputPath, envJsContent);

console.log('✅ Generated public/env.js with environment configuration');
console.log('Environment variables:');
Object.entries(envVars).forEach(([key, value]) => {
  const maskedValue = key.includes('KEY') || key.includes('TOKEN')
    ? value ? `${value.substring(0, 10)}...` : '(empty)'
    : value || '(empty)';
  console.log(`  - ${key}: ${maskedValue}`);
});
