/**
 * 🔍 SEO Programmatic Audit Tool
 * 
 * This tool verifies that the programmatic SEO pages are being correctly 
 * generated by the database and accessible via the API.
 * 
 * Usage: pnpm tsx apps/web/tools/seo/audit-seo-pages.ts
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function auditSeoPages() {
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║  🔍 Auditing Programmatic SEO Infrastructure             ║');
  console.log('╚══════════════════════════════════════════════════════════╝\n');

  // 1. Check Materialized View
  console.log('1. Checking mv_seo_landing_pages...');
  const { data: mvData, error: mvError } = await supabase
    .from('mv_seo_landing_pages')
    .select('brand, city, car_count')
    .limit(5);

  if (mvError) {
    console.error('❌ Error querying materialized view:', mvError.message);
  } else {
    console.log(`✅ View is active. Found ${mvData?.length || 0} sample combinations.`);
    mvData?.forEach(row => {
      console.log(`   - ${row.brand} in ${row.city}: ${row.car_count} cars`);
    });
  }

  // 2. Check RPC Logic
  console.log('\n2. Testing get_seo_page_data RPC...');
  if (mvData && mvData.length > 0) {
    const sample = mvData[0];
    const { data: rpcData, error: rpcError } = await supabase.rpc('get_seo_page_data', {
      p_segment1: sample.brand.toLowerCase(),
      p_segment2: sample.city.toLowerCase()
    });

    if (rpcError) {
      console.error('❌ RPC Error:', rpcError.message);
    } else {
      console.log('✅ RPC is working correctly.');
      console.log(`   - H1: ${rpcData.h1}`);
      console.log(`   - Meta Title: ${rpcData.meta_title}`);
      console.log(`   - Cars returned: ${rpcData.cars?.length || 0}`);
    }
  } else {
    console.log('⚠️ Skipping RPC test (no data in view).');
  }

  // 3. Check Sitemap Logic
  console.log('\n3. Checking Sitemap Generation...');
  const { data: smData, error: smError } = await supabase.rpc('get_all_seo_urls');

  if (smError) {
    console.error('❌ Sitemap RPC Error:', smError.message);
  } else {
    console.log(`✅ Sitemap RPC returned ${smData?.length || 0} URLs.`);
  }

  console.log('\n✨ Audit Complete.');
}

auditSeoPages().catch(err => {
  console.error('Fatal error during audit:', err);
  process.exit(1);
});
