import { execSync } from 'child_process';

/**
 * Configuration
 */
const CONFIG = {
    SENTRY_ORG: 'ecu-iu',
    SENTRY_PROJECT: 'autorenta',
    GITHUB_LABEL: 'sentry-automated',
};

interface SentryIssue {
    id: string;
    title: string;
    lastSeen: string;
    level: string;
}

/**
 * Execute shell command and return output
 */
function runCommand(command: string): string {
    try {
        return execSync(command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    } catch (error) {
        // Sentry CLI might exit with non-zero if no issues found or other minor things,
        // but usually we want to know. For now, let's return empty if it fails strictly.
        // Or better, rethrow if it's a real error.
        return '';
    }
}

/**
 * Fetch unresolved issues from Sentry
 */
function getSentryIssues(): SentryIssue[] {
    console.log('🔍 Fetching unresolved issues from Sentry...');

    // Note: sentry-cli issues list output is a table. We need to parse it.
    // There is no easy JSON flag for 'issues list' in standard sentry-cli versions apparently, 
    // so we parse the text table.

    const cmd = `sentry-cli issues list --org ${CONFIG.SENTRY_ORG} --project ${CONFIG.SENTRY_PROJECT} --status unresolved`;
    const output = runCommand(cmd);

    if (!output) {
        console.log('No issues found or failed to fetch.');
        return [];
    }

    const lines = output.split('\n');
    const issues: SentryIssue[] = [];

    // Table structure usually:
    // +------------+--------------+-------...
    // | ID         | Status       | Title ...
    // +------------+--------------+-------...
    // | 12345      | unresolved   | Error ...

    for (const line of lines) {
        const cleanLine = line.trim();
        if (cleanLine.startsWith('+') || cleanLine.startsWith('| ID')) continue;
        if (!cleanLine.startsWith('|')) continue;

        const parts = cleanLine.split('|').map(p => p.trim());
        // parts[0] is empty (before first |), parts[1] is ID, parts[2] is Status, parts[3] is Title...

        // Adjust index based on actual output observation:
        // | 7206930540 | AUTORENTA-2  | Error: Style is not ... | 2026-01-21... | unresolved | error   |
        // indices: 0:empty, 1:ID, 2:ShortID, 3:Title, 4:LastSeen, 5:Status, 6:Level, 7:empty

        if (parts.length >= 7) {
            const id = parts[1];
            const title = parts[3];
            const lastSeen = parts[4];
            const level = parts[6];

            if (id && title) {
                issues.push({ id, title, lastSeen, level });
            }
        }
    }

    console.log(`✅ Found ${issues.length} unresolved issues in Sentry.`);
    return issues;
}

/**
 * Check if issue exists in GitHub
 */
function githubIssueExists(sentryIssueId: string): boolean {
    // Search for the Sentry Issue ID in GitHub issues
    // We'll verify if any issue contains the Sentry ID in the body
    const cmd = `gh issue list --search "${sentryIssueId} in:body" --json number`;
    const output = runCommand(cmd);
    try {
        const results = JSON.parse(output);
        return results.length > 0;
    } catch {
        return false;
    }
}

/**
 * Create issue in GitHub
 */
function createGithubIssue(issue: SentryIssue) {
    console.log(`Creating GitHub issue for Sentry ID: ${issue.id}...`);

    const sentryUrl = `https://${CONFIG.SENTRY_ORG}.sentry.io/issues/${issue.id}`;
    const title = `[Sentry] ${issue.title.replace(/\|/g, '-')}`; // Avoid pipe confusion if any
    const body = `
**Sentry Issue:** [${issue.id}](${sentryUrl})
**Last Seen:** ${issue.lastSeen}
**Level:** ${issue.level}

### Error Details
${issue.title}

---
*Auto-generated by Sentry-to-GitHub automation tool*
  `.trim();

    // Create issue
    // Using spawn/exec with proper escaping is tricky, so we'll pass body via stdin or just be careful.
    // gh issue create accepts --body-file or just --body. 
    // We'll use a temp file logic if needed, but for simple text passed in arg it might be ok if escaped.
    // Actually, execSync might fail with newlines in args depending on shell. 
    // Safer to use built-in child_process.spawnSync? Or just simple string for now.

    // Let's use `gh issue create` with data.
    // We need to escape double quotes in body for bash string.
    const safeBody = body.replace(/"/g, '\\"');
    const safeTitle = title.replace(/"/g, '\\"');

    const label = CONFIG.GITHUB_LABEL;

    const cmd = `gh issue create --title "${safeTitle}" --body "${safeBody}" --label "${label}"`;

    try {
        const result = execSync(cmd, { encoding: 'utf8' });
        console.log(`✅ GitHub Issue created: ${result.trim()}`);
    } catch (err: any) {
        console.error(`❌ Failed to create issue associated with Sentry ID ${issue.id}`);
    }
}

/**
 * Main
 */
async function main() {
    console.log('🚀 Starting Sentry-to-GitHub sync...');

    // 1. Get Issues
    const issues = getSentryIssues();

    if (issues.length === 0) {
        console.log('No issues to process.');
        return;
    }

    // 2. Process each issue
    for (const issue of issues) {
        const exists = githubIssueExists(issue.id);
        if (exists) {
            console.log(`⏭️  Skipping Sentry ID ${issue.id} (already exists in GitHub)`);
        } else {
            createGithubIssue(issue);
        }
    }

    console.log('✅ Sync completed.');
}

main();
