-- ============================================================================
-- FIX: Add returned_at to owner_bookings and my_bookings views
-- Date: 2026-01-11
-- Problem: Owner check-out page needs returned_at to skip markAsReturned step
-- ============================================================================

-- Drop views first (required when adding new columns)
DROP VIEW IF EXISTS owner_bookings;
DROP VIEW IF EXISTS my_bookings;

-- Recreate owner_bookings view with returned_at
CREATE VIEW owner_bookings AS
SELECT
  b.id,
  b.car_id,
  b.renter_id,
  b.start_at,
  b.end_at,
  b.status,
  b.total_amount,
  b.currency,
  b.created_at,
  b.updated_at,
  b.guarantee_type,
  b.guarantee_amount_cents,
  b.deposit_amount_cents,
  b.risk_snapshot_booking_id,
  b.risk_snapshot_date,
  b.requires_revalidation,
  b.hold_authorization_id,
  b.hold_expires_at,
  b.reauthorization_count,
  b.payment_mode,
  b.coverage_upgrade,
  b.authorized_payment_id,
  b.wallet_lock_id,
  b.total_price_ars,
  b.idempotency_key,
  b.payment_split_completed,
  b.payment_split_validated_at,
  b.owner_payment_amount,
  b.platform_fee,
  b.pickup_location_lat,
  b.pickup_location_lng,
  b.dropoff_location_lat,
  b.dropoff_location_lng,
  b.delivery_required,
  b.delivery_distance_km,
  b.delivery_fee_cents,
  b.distance_risk_tier,
  b.payment_provider,
  b.payment_preference_id,
  b.payment_init_point,
  b.provider_split_payment_id,
  b.provider_collector_id,
  b.days_count,
  b.nightly_rate_cents,
  b.subtotal_cents,
  b.insurance_cents,
  b.fees_cents,
  b.discounts_cents,
  b.total_cents,
  b.breakdown,
  b.payment_id,
  b.expires_at,
  b.paid_at,
  b.cancellation_policy_id,
  b.cancellation_fee_cents,
  b.cancelled_at,
  b.cancellation_reason,
  b.has_dynamic_pricing,
  b.dynamic_price_snapshot,
  b.price_locked_until,
  b.price_lock_token,
  b.google_calendar_event_id,
  b.calendar_synced_at,
  b.calendar_sync_enabled,
  b.payout_status,
  b.payout_date,
  b.platform_fee_collected,
  b.owner_amount_paid,
  b.payout_retry_count,
  b.payout_error_message,
  b.mercadopago_split_id,
  b.risk_snapshot_id,
  -- NEW: Add returned_at for owner check-out flow
  b.returned_at,
  b.inspection_status,
  b.owner_confirmed_delivery,
  b.renter_confirmed_payment,
  -- Car details
  c.title AS car_title,
  c.brand AS car_brand,
  c.model AS car_model,
  c.location_lat AS car_location_lat,
  c.location_lng AS car_location_lng,
  -- Renter details
  pr.full_name AS renter_name,
  pr.avatar_url AS renter_avatar,
  -- Payment details
  pay.status AS payment_status,
  pay.provider AS payment_table_provider
FROM bookings b
JOIN cars c ON c.id = b.car_id
LEFT JOIN profiles pr ON pr.id = b.renter_id
LEFT JOIN payments pay ON pay.id = b.payment_id
WHERE c.owner_id = auth.uid();

-- Also recreate my_bookings view with returned_at
CREATE VIEW my_bookings AS
SELECT
  b.id,
  b.car_id,
  b.renter_id,
  b.start_at,
  b.end_at,
  b.status,
  b.total_amount,
  b.currency,
  b.created_at,
  b.updated_at,
  b.guarantee_type,
  b.guarantee_amount_cents,
  b.deposit_amount_cents,
  b.risk_snapshot_booking_id,
  b.risk_snapshot_date,
  b.requires_revalidation,
  b.hold_authorization_id,
  b.hold_expires_at,
  b.reauthorization_count,
  b.payment_mode,
  b.coverage_upgrade,
  b.authorized_payment_id,
  b.wallet_lock_id,
  b.total_price_ars,
  b.idempotency_key,
  b.payment_split_completed,
  b.payment_split_validated_at,
  b.owner_payment_amount,
  b.platform_fee,
  b.pickup_location_lat,
  b.pickup_location_lng,
  b.dropoff_location_lat,
  b.dropoff_location_lng,
  b.delivery_required,
  b.delivery_distance_km,
  b.delivery_fee_cents,
  b.distance_risk_tier,
  b.payment_provider,
  b.payment_preference_id,
  b.payment_init_point,
  b.provider_split_payment_id,
  b.provider_collector_id,
  b.days_count,
  b.nightly_rate_cents,
  b.subtotal_cents,
  b.insurance_cents,
  b.fees_cents,
  b.discounts_cents,
  b.total_cents,
  b.breakdown,
  b.payment_id,
  b.expires_at,
  b.paid_at,
  b.cancellation_policy_id,
  b.cancellation_fee_cents,
  b.cancelled_at,
  b.cancellation_reason,
  b.has_dynamic_pricing,
  b.dynamic_price_snapshot,
  b.price_locked_until,
  b.price_lock_token,
  b.google_calendar_event_id,
  b.calendar_synced_at,
  b.calendar_sync_enabled,
  b.payout_status,
  b.payout_date,
  b.platform_fee_collected,
  b.owner_amount_paid,
  b.payout_retry_count,
  b.payout_error_message,
  b.mercadopago_split_id,
  b.risk_snapshot_id,
  -- NEW: Add returned_at for check-out flow
  b.returned_at,
  b.inspection_status,
  b.owner_confirmed_delivery,
  b.renter_confirmed_payment,
  -- Car details
  c.title AS car_title,
  c.brand AS car_brand,
  c.model AS car_model,
  c.location_lat AS car_location_lat,
  c.location_lng AS car_location_lng,
  c.owner_id AS car_owner_id,
  -- Owner details
  po.full_name AS owner_name,
  po.avatar_url AS owner_avatar,
  -- Payment details
  pay.status AS payment_status,
  pay.provider AS payment_table_provider
FROM bookings b
JOIN cars c ON c.id = b.car_id
LEFT JOIN profiles po ON po.id = c.owner_id
LEFT JOIN payments pay ON pay.id = b.payment_id
WHERE b.renter_id = auth.uid();

-- ============================================================================
DO $$ BEGIN RAISE NOTICE '✅ Views updated with returned_at, inspection_status, and bilateral confirmation fields'; END $$;
